sadmin/controllers/BankController.php
<?php

namespace sadmin\controllers;

use Yii;
use common\models\TblBanks;
use common\models\TblBanksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;

/**
 * BankController implements the CRUD actions for TblBanks model.
 */
class BankController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view', 'update', 'delete', 'create'],
                        'roles'   => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->identity->role_id == User::ROLE_SADMIN) {
                                return true;
                            }
                            return false;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all TblBanks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblBanksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TblBanks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TblBanks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TblBanks();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TblBanks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TblBanks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TblBanks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TblBanks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TblBanks::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

sadmin/controllers/ConfigController.php
<?php

namespace sadmin\controllers;

use Yii;
use common\models\TblConfig;
use common\models\TblConfigSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;

/**
 * ConfigController implements the CRUD actions for TblConfig model.
 */
class ConfigController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view', 'update', 'delete', 'create'],
                        'roles'   => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->identity->role_id == User::ROLE_SADMIN) {
                                return true;
                            }
                            return false;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all TblConfig models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblConfigSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TblConfig model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TblConfig model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TblConfig();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TblConfig model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TblConfig model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TblConfig model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TblConfig the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TblConfig::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

sadmin/controllers/SiteController.php
<?php
namespace sadmin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Request;
use yii\data\Pagination;
use common\models\LoginForm;
use common\models\User;
use common\models\TblPaidTransaction;
use common\models\TblWallets;
use common\models\TblRank;
use common\models\TblConfig;
use common\models\TblHistoryBonus;
use common\models\TblProducts;
use common\models\TblProductOrders;
use common\models\TblCountry;
use common\models\PasswordResetRequestForm;
use common\models\ResetPasswordForm;
use common\helpers\generalHelper;
use common\helpers\processHelper;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['dashboard', 'product', 'income','history','update-bonus','export'],
                        'allow' => true,
                        'roles'   => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->identity->role_id == User::ROLE_SADMIN) {
                                return true;
                            }
                            return false;
                        }
                    ],
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionProduct()
    {
        $countries = TblCountry::find()->all();
        foreach($countries as $key => $country){
            $products = TblProducts::find()->joinWith(["prices"])->where("country_id = ".$country->id)->all();
            foreach ($products as $k => $v) {
                $products[$k]->today_orders = count(TblProductOrders::find()->where("product_id = ".$v->id." AND created_at >= ".strtotime(date('Y-m-d')))->all());
            }
            $countries[$key]->today_orders = $products;
        }
        return $this->render('product',[
            'data' => $countries
        ]);
    }

    private $tm = [];

    public function actionUp()
    {
        $this->recursive(9);
        $ids = implode(",", $this->tm);
        Yii::$app->db->createCommand('UPDATE tbl_users SET level = level + 1 WHERE id IN ('.$ids.')')->execute();
        //return $this->render('index');
    }

    function recursive($id){
        $x = User::find()->where('id = '.$id)->one();
        if($x){
            $this->tm[] = $x->parent_id;
            if($x->parent_id >0)
                $this->recursive($x->parent_id);    
        }
    }

    public function actionIndex()
    {
        if(Yii::$app->user->identity->role_id == User::ROLE_ADMIN)
            return $this->redirect(['user/index']);

        if(Yii::$app->user->identity->role_id == User::ROLE_PADMIN)
            return $this->redirect(['orders/index']);

        $countries = TblCountry::find()->all();
        foreach($countries as $key => $country){
            $country_data = processHelper::countryAna($country->id);
            $countries[$key]->today_orders = $country_data['order_today'];
            $countries[$key]->after_bonus = $country_data['bonus_today'];
            $countries[$key]->today_registers = count(User::find()->where(['>=','created_at',strtotime(date('Y-m-d'))])->andWhere(['=','tbl_users.country_id', $country->id])->all());
            $countries[$key]->total_user = count(User::find()->where(['=','tbl_users.country_id', $country->id])->all());
            $countries[$key]->active_user = count(User::find()->where(['=','tbl_users.country_id', $country->id])->andWhere(['>','rank_id',0])->all());
        }
        return $this->render('index',[
            'data' => $countries
        ]);
    }

    public function actionDashboard()
    {
        return $this->render('dashboard');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
    public function actionHistory()
    {
        $query = TblHistoryBonus::find()->orderBy('created_at desc');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
        ->limit($pages->limit)
        ->all();

        return $this->render('history', [
             'models' => $models,
             'pages' => $pages,
        ]);
    }
    public function actionUpdateBonus()
    {
        $id = $_GET['type'];
        if($id==1){
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction(); //get parent user
            try{
                $data = TblHistoryBonus::find()->select([
                    '*','SUM(amount) AS total'
                ])->where(['=','payment_status','1'])
                  ->andWhere(['=','wallet',TblWallets::TYPE_BONUS])
                  ->groupBy('user_id')->all();
                foreach($data as $user_bonus){
                    $wallet = TblWallets::find()->where(['user_id' => $user_bonus->user_id])
                                            ->andWhere([ 'type'=> TblWallets::TYPE_BONUS ])->one();
                    $wallet->amount -= $user_bonus->total;
                    $wallet->save();
                }
                TblHistoryBonus::updateAll(['payment_status' => '2'],[ 'payment_status' => '1']);
                $transaction->commit();
            } catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            }
        }else{
            TblHistoryBonus::updateAll(['payment_status' => '1'],[ 'payment_status' => '0']);
        }
        echo 'Done <input action="action" type="button" value="Back to report" onclick="history.go(-1);" />';
    }
    public function actionExport()
    {
        $countries = TblCountry::find()->all();
        $objPHPExcel = new \PHPExcel();
        foreach($countries as $key => $country){
            $bonus_history_processing = TblHistoryBonus::find()->select([
                    '*',
                    'SUM(amount) AS total'
                ])->leftJoin('tbl_users','`tbl_users`.`id` = `tbl_history_bonus`.`user_id`')
                  ->andWhere(['=','payment_status','1'])
                  ->andWhere(['=','wallet',TblWallets::TYPE_BONUS])
                  ->andWhere(['=','tbl_users.country_id',$country->id])
                  ->groupBy('user_id')->orderBy('total desc')->all();
            $this->excelSheet($key,$bonus_history_processing,$objPHPExcel,$country->name);
        }
        $objPHPExcel->setActiveSheetIndex(0);
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.date("d-m-Y").'-report.xlsx"');
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');
        // If you're serving to IE over SSL, then the following may be needed
        header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
        header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header ('Pragma: public'); // HTTP/1.0
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        $objWriter->save('php://output');
    }
    function excelSheet($key,$data,&$objPHPExcel,$title){
        $objWorkSheet = $objPHPExcel->createSheet($key); //Setting index when creating
        //Write cells
        $objWorkSheet->setCellValue('A1', '#')
                    ->setCellValue('B1', 'User')
                    ->setCellValue('C1', 'Fullname')
                    ->setCellValue('D1', 'Bank Name')
                    ->setCellValue('E1', 'Bank Account')
                    ->setCellValue('F1', 'Country')
                    ->setCellValue('G1', 'Before Tax (USD)')
                    ->setCellValue('H1', 'After Tax (USD)')
                    ->setCellValue('I1', 'Tax (%)');
        foreach($data as $key => $his){
            if($his->total >0){
                $user = $his->getUser()->one();
                $country =  $user->getTblCountry()->one();
                $bank = $user->getTblBanks()->one();
                $sheet = $key + 2;
                $objWorkSheet->setCellValue('A'.$sheet, $key+1)
                            ->setCellValue('B'.$sheet, isset($user->username) ? $user->username : '')
                            ->setCellValue('C'.$sheet, isset($user->fullname) ? $user->fullname : '')

sadmin/views/layouts/empty.php
<?=$content;?>

sadmin/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
use common\models\User;
use yii\helpers\Url;

AppAsset::register($this);
?>
    <?php $this->beginPage() ?>
        <!doctype html>
        <html lang="<?= Yii::$app->language ?>">

        <head>
            <meta charset="utf-8" />
            <?= Html::csrfMetaTags() ?>
                <title>
                    <?= Html::encode($this->title) ?>
                </title>
                <?php $this->head() ?>
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <!-- Bootstrap -->
                <link href="/admin/files/bootstrap/css/bootstrap.min.css" rel="stylesheet">
                <!-- styles -->
                <link href="/admin/files/css/styles.css" rel="stylesheet">
        </head>

        <body>
            <?php $this->beginBody() ?>
                <nav class="navbar nav-moringga">
                    <div class="container">
                        <div class="navbar-header">
                            <a href="/admin" style="padding:5px;">
                                <img src="/admin/files/img/logo.png" style="opacity: 0" height="30" width="0" alt="logo">
                                <big><big>MORINGNA ASIA</big></big> | 
                            </a>
                            <span class="title-page"><?=$this->title;?></span>

                        </div>
                        <ul class="nav navbar-right">
                            <?php if(Yii::$app->user->identity != null && Yii::$app->user->identity->role_id == User::ROLE_SADMIN):?>
                                <li class="item">
                                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Report<b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Dashboard', ['site/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('History Bonus', ['site/history'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('History Day', ['history-day/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Dashboard Product', ['site/product'], []) ?>
                                        </li>
                                    </ul>
                                </li>
                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Config', ['config/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Country', ['country/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Currency', ['currency/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Bank', ['bank/index'], []) ?>
                                        </li>
                                    </ul>
                                </li>

                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Users Management', ['user/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Transactions', ['transactions/index'], []) ?>
                                        </li>
                                    </ul>
                                </li>

                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Products Management', ['products/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Categories', ['productcategory/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Orders', ['orders/index'], []) ?>
                                        </li>
                                    </ul>
                                </li>

                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Profile', ['user/profile'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Logout', ['site/logout'], []) ?>
                                        </li>
                                    </ul>
                                </li>
                                <?php endif; ?>
                            <?php if(Yii::$app->user->identity != null && Yii::$app->user->identity->role_id == User::ROLE_ADMIN):?>
     
                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Users Management', ['user/index'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Transactions', ['transactions/index'], []) ?>
                                        </li>
                                    </ul>
                                </li>


                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Profile', ['user/profile'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Logout', ['site/logout'], []) ?>
                                        </li>
                                    </ul>
                                </li>
                                <?php endif; ?>
                            <?php if(Yii::$app->user->identity != null && Yii::$app->user->identity->role_id == User::ROLE_PADMIN):?>

                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Orders', ['orders/index'], []) ?>
                                        </li>
                                    </ul>
                                </li>

                                <li class="item dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                    <ul class="dropdown-menu animated fadeInUp">
                                        <li>
                                            <?= Html::a('Profile', ['user/profile'], []) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('Logout', ['site/logout'], []) ?>
                                        </li>
                                    </ul>
                                </li>
                                <?php endif; ?>
                        </ul>
                    </div>
                </nav>

                <div class="container page-content">
                    <?= $content ?>
                </div>

                <footer class="footer">
                    <div class="container">
                        <div class="copy text-center">
                            Copyright 2016 <a href='/'>Moringna Asia</a> All rights reserved
                        </div>
                    </div>
                </footer>
                <script src="/admin/files/js/jquery.js"></script>
                <script src="/admin/files/bootstrap/js/bootstrap.min.js"></script>
                <script src="/admin/files/js/custom.js"></script>
                <script src="/admin/files/js/app.js"></script>
                <script type="text/javascript">
                    var checkAction = false;
                    var countInt = 0;
                    setInterval(function(){
                        if(countInt >= 5*60){
                            location.href="<?=Url::to(['site/logout']);?>";
                        }
                        countInt++;
                    }, 1000);

                    $(window).keyup(function(){
                        countInt = 0;
                    })

                    $(window).mousemove(function(){
                        countInt = 0;
                    })
                </script>
                <?php $this->endBody() ?>
        </body>

        </html>
        <?php $this->endPage() ?>